### ISSUE TITLE
`Tag` edit type not working as expected

### ISSUE THREAD

**Issue by xabriel** [geohci/edit-types#75]
Version: 2.0.0

When trying to plot edit types, I noticed that the set of unique edit types for `eswiki` was not as expected.

Unique edit types:
```
$ wc -l part-00000-8d17789a-7671-4f82-a97c-ff8966790a96-c000.csv 
1919
```

If we consider all edit types but `Tag`s, we get a reasonable set:
```
$ cat part-00000-8d17789a-7671-4f82-a97c-ff8966790a96-c000.csv | grep -v Tag
Paragraph
Template
Whitespace
Text Formatting
Gallery
Table Element
Table
Argument
Punctuation
Section
Reference
List
Sentence
HTMLEntity
Wikilink
ExternalLink
Category
Word
Media
Heading
Comment
```

But for `Tag`s, we get what seems to be runaway behavior:
```
$ cat part-00000-8d17789a-7671-4f82-a97c-ff8966790a96-c000.csv | grep Tag
...
Timlaine Tag
Brujo Tag
Marquee Tag
Lojvrnuohedwigodewoijdqjpidejipqdpjidewbr Tag
Aston Tag
Reflo Tag
Rotf090418109.jpg Tag
Green Tag
B)r Tag
Over Tag
Legend Tag
Small Tag
Lh Tag
21 Tag
Referencss Tag
Brhdhwjwjshsvhehdhdhrbhejejsjsjshjehdhdkskshhsjfjekskjskajwjshdhjdjdjdjsjsjjsjsjsjdhehehsjskosksbs Tag
Apellido2 Tag
Refbienvenidos Tag
Tempmax Tag
Openservicedescription Tag
Big Tag
Width Tag
Brfsd Tag
Born Tag
Refy Tag
...
```

Here is how many different `Tag`s I found:
```
$ cat part-00000-8d17789a-7671-4f82-a97c-ff8966790a96-c000.csv | grep Tag | wc -l
1898
```

**Comment by xabriel** [comment]
@geohci pinging for advice on whether this is expected behavior or not. Thanks!

**Comment by geohci** [comment]
Ahh sorry thanks for the ping @xabriel ! Yes that is expected behavior but I'm definitely open to suggestions for alternative behavior that would be better. Essentially wikitext markup allows both arbitrary HTML tags and malformed tags too so you essentially have an infinite number of things like `<div>`, `<meta>`, really anything between `<>` that can appear in the markup. I originally chose to preserve the tag name (e.g. `<div>` -> `Div Tag`) but I'm seeing that a lot of them are junk so maybe I should just squash them all down to `Other  Tag` or something generic like that?

**Comment by xabriel** [comment]
>  Essentially wikitext markup allows both arbitrary HTML tags and malformed tags too

Well that sounds complicated! 😄  

> maybe I should just squash them all down to Other Tag or something generic like that?

That is what I was considering to do in my code! So I agree that if the element is not well known and we are doing `SimpleEditTypes` we should squash them. I don't know though what that 'well known' set should be?

**Comment by geohci** [comment]
> I don't know though what that 'well known' set should be?

I already extracted some that I could find that had clear/interesting meaning ([code](https://github.com/geohci/edit-types/blob/main/mwedittypes/constants.py#L7-L10)) and that's probably good enough for now and I can leave the others in a generic Other Tag category. Always easy to adjust later. I suspect the ones like `Small` that show up on that list despite already being caught by me are actually different capitalizations -- e.g., `<Small>` instead of `<small>` -- and I could probably make that check case-insensitive.
